version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:5432/

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - web_network

  web_api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash start-server.sh
    depends_on:
      - postgres
    ports:
      - '3000:3000'
      - '5555:5555'
    networks:
      - web_network

volumes:
  postgres:


networks:
  web_network:
    driver: bridge
